/**
 * The typed edge between the window and the core.
 *
 * Every function here is one name from `booker_core::ipc::COMMANDS`, and
 * every type it speaks is generated from the Rust contracts by `ts-rs`
 * (`cargo test -p booker-core export_bindings`). Nothing in the UI calls
 * `invoke` directly: a command name spelled wrong is a runtime error at the
 * far end, and a payload shaped by hand is a contract that drifts.
 *
 * The bindings are generated, git-ignored and regenerated by the build, so
 * a change to a Rust contract turns into a TypeScript error here rather
 * than into a surprise at runtime.
 */

import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

import type { ChapterText } from "./bindings/ChapterText";
import type { CompileResult } from "./bindings/CompileResult";
import type { ProjectChanged } from "./bindings/ProjectChanged";
import type { ProjectInfo } from "./bindings/ProjectInfo";
import type { Revision } from "./bindings/Revision";

/** Open a project folder. The project's own faults come back inside the
 *  answer, in `diagnostics`; a rejected promise means the folder itself
 *  could not be read. */
export function openProject(root: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("open_project", { root });
}

/** Describe the open project, or `null` when none is open. */
export function projectInfo(): Promise<ProjectInfo | null> {
  return invoke<ProjectInfo | null>("project_info");
}

/** Close the open project. Closing nothing is not an error. */
export function closeProject(): Promise<void> {
  return invoke<void>("close_project");
}

/** The folders this window has opened before, newest first. */
export function recentProjects(): Promise<string[]> {
  return invoke<string[]>("recent_projects");
}

/** Lay the book out without writing anything. A book with errors returns a
 *  result with no pages and the errors in `diagnostics`. */
export function compile(): Promise<CompileResult> {
  return invoke<CompileResult>("compile");
}

/** Lay the book out and write a PDF to `destination`. */
export function exportPdf(
  project: ProjectInfo,
  destination: string,
): Promise<CompileResult> {
  return invoke<CompileResult>("export_pdf", {
    request: {
      project: project.project,
      revision: project.revision,
      destination,
    },
  });
}

/** One chapter's source, for the editor pane. */
export function readChapter(path: string): Promise<ChapterText> {
  return invoke<ChapterText>("read_chapter", { path });
}

/** Write a chapter back. What comes back describes the book as it now is. */
export function saveChapter(path: string, text: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("save_chapter", { path, text });
}

/** Read the project from disk again, after something outside changed it.
 *  Returns null when the project was closed in between. */
export function reloadProject(): Promise<ProjectInfo | null> {
  return invoke<ProjectInfo | null>("reload_project");
}

/**
 * The URL of one page image, in the shape `booker_core::ipc::page_image_url`
 * builds and `app/src-tauri/src/protocol.rs` answers.
 *
 * Spelled here rather than imported because it is a URL, not a command —
 * the point of it is that page images do *not* go through IPC. The two
 * spellings are kept in step by a test.
 */
export function pageImageUrl(
  revision: Revision,
  page: number,
  scale: number,
  format: "png" | "svg" = "png",
): string {
  return `booker://page/${revision}/${page}@${scale}x.${format}`;
}

/** The project on disk has moved on — an agent, another editor, a checkout.
 *  Wave 1 track C is what starts emitting this; the listener is here so the
 *  window is already written to expect it. */
export function onProjectChanged(
  handler: (changed: ProjectChanged) => void,
): Promise<UnlistenFn> {
  return listen<ProjectChanged>("project-changed", (event) => handler(event.payload));
}

/** A menu item was chosen. The payload is the item's id, as `menu.rs`
 *  spells it, so the menu and the window's own buttons run one code path. */
export function onMenu(handler: (id: string) => void): Promise<UnlistenFn> {
  return listen<string>("menu", (event) => handler(event.payload));
}
