/**
 * The typed edge between the window and the core.
 *
 * Every function here is one name from `booker_core::ipc::COMMANDS`, and
 * every type it speaks is generated from the Rust contracts by `ts-rs`
 * (`cargo test -p booker-core export_bindings`). Nothing in the UI calls
 * `invoke` directly: a command name spelled wrong is a runtime error at the
 * far end, and a payload shaped by hand is a contract that drifts.
 *
 * The bindings are generated, git-ignored and regenerated by the build, so
 * a change to a Rust contract turns into a TypeScript error here rather
 * than into a surprise at runtime.
 */

import { invoke } from "@tauri-apps/api/core";

import type { ProjectInfo } from "./bindings/ProjectInfo";

/** Open a project folder. The project's own faults come back inside the
 *  answer, in `diagnostics`; a rejected promise means the folder itself
 *  could not be read. */
export function openProject(root: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("open_project", { root });
}

/** Describe the open project, or `null` when none is open. */
export function projectInfo(): Promise<ProjectInfo | null> {
  return invoke<ProjectInfo | null>("project_info");
}

/** Close the open project. Closing nothing is not an error. */
export function closeProject(): Promise<void> {
  return invoke<void>("close_project");
}
