/**
 * The typed edge between the window and the core.
 *
 * Every function here is one name from `booker_core::ipc::COMMANDS`, and
 * every type it speaks is generated from the Rust contracts by `ts-rs`
 * (`cargo test -p booker-core export_bindings`). Nothing in the UI calls
 * `invoke` directly: a command name spelled wrong is a runtime error at the
 * far end, and a payload shaped by hand is a contract that drifts.
 *
 * The bindings are generated, git-ignored and regenerated by the build, so
 * a change to a Rust contract turns into a TypeScript error here rather
 * than into a surprise at runtime.
 */

import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

import type { ChapterText } from "./bindings/ChapterText";
import type { PagePoint } from "./bindings/PagePoint";
import type { CompileResult } from "./bindings/CompileResult";
import type { ProjectChanged } from "./bindings/ProjectChanged";
import type { ProjectInfo } from "./bindings/ProjectInfo";
import type { Revision } from "./bindings/Revision";
import type { SaveOutcome } from "./bindings/SaveOutcome";
import type { SourceLocation } from "./bindings/SourceLocation";

/** Open a project folder. The project's own faults come back inside the
 *  answer, in `diagnostics`; a rejected promise means the folder itself
 *  could not be read. */
export function openProject(root: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("open_project", { root });
}

/** Describe the open project, or `null` when none is open. */
export function projectInfo(): Promise<ProjectInfo | null> {
  return invoke<ProjectInfo | null>("project_info");
}

/** Close the open project. Closing nothing is not an error. */
export function closeProject(): Promise<void> {
  return invoke<void>("close_project");
}

/** The folders this window has opened before, newest first. */
export function recentProjects(): Promise<string[]> {
  return invoke<string[]>("recent_projects");
}

/** Lay the book out without writing anything. A book with errors returns a
 *  result with no pages and the errors in `diagnostics`. */
export function compile(): Promise<CompileResult> {
  return invoke<CompileResult>("compile");
}

/** Lay the book out and write a PDF to `destination`. */
export function exportPdf(
  project: ProjectInfo,
  destination: string,
): Promise<CompileResult> {
  return invoke<CompileResult>("export_pdf", {
    request: {
      project: project.project,
      revision: project.revision,
      destination,
    },
  });
}

/** One chapter's source, for the editor pane. */
export function readChapter(path: string): Promise<ChapterText> {
  return invoke<ChapterText>("read_chapter", { path });
}

/** Write a chapter back. `base` is the text the editor last loaded or
 *  saved: when the file on disk is no longer that, someone else changed it,
 *  nothing is written, and the answer is a conflict carrying both versions. */
export function saveChapter(path: string, text: string, base: string): Promise<SaveOutcome> {
  return invoke<SaveOutcome>("save_chapter", { path, text, base });
}

/** Add a chapter after `after` (or at the end), titled `title`, containing
 *  `text` (or just its title). Returns its path and the book as it now is. */
export function addChapter(
  after: string | null,
  title: string,
  text: string | null = null,
): Promise<[string, ProjectInfo]> {
  return invoke<[string, ProjectInfo]>("add_chapter", { after, title, text });
}

/** Move a chapter to `index` in the reading order. */
export function moveChapter(path: string, index: number): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("move_chapter", { path, index });
}

/** Take a chapter out of the book. Its file stays in the folder. */
export function removeChapter(path: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("remove_chapter", { path });
}

/** Give a chapter a new title: its first heading is rewritten. */
export function renameChapter(path: string, title: string): Promise<ProjectInfo> {
  return invoke<ProjectInfo>("rename_chapter", { path, title });
}

/** Click-to-source: the place in a chapter that produced what is drawn at
 *  `point`, or null for a margin, a page number, the contents. Answered
 *  from the last layout. */
export function sourceAt(point: PagePoint): Promise<SourceLocation | null> {
  return invoke<SourceLocation | null>("source_at", { point });
}

/** Cursor-to-page: where a place in a chapter landed — usually one point,
 *  none when nothing there is printed. */
export function pagesAt(location: SourceLocation): Promise<PagePoint[]> {
  return invoke<PagePoint[]>("pages_at", { location });
}

/** Read the project from disk again, after something outside changed it.
 *  Returns null when the project was closed in between. */
export function reloadProject(): Promise<ProjectInfo | null> {
  return invoke<ProjectInfo | null>("reload_project");
}

/**
 * The URL of one page image, in the shape `booker_core::ipc::page_image_url`
 * builds and `app/src-tauri/src/protocol.rs` answers.
 *
 * Spelled here rather than imported because it is a URL, not a command —
 * the point of it is that page images do *not* go through IPC. The two
 * spellings are kept in step by a test.
 */
export function pageImageUrl(
  revision: Revision,
  page: number,
  scale: number,
  format: "png" | "svg" = "png",
): string {
  return `booker://page/${revision}/${page}@${scale}x.${format}`;
}

/** The project on disk has moved on — an agent, another editor, a checkout,
 *  or the echo of a write this window made. The watcher coalesces a burst
 *  of changes into one of these. */
export function onProjectChanged(
  handler: (changed: ProjectChanged) => void,
): Promise<UnlistenFn> {
  return listen<ProjectChanged>("project-changed", (event) => handler(event.payload));
}

/** A menu item was chosen. The payload is the item's id, as `menu.rs`
 *  spells it, so the menu and the window's own buttons run one code path. */
export function onMenu(handler: (id: string) => void): Promise<UnlistenFn> {
  return listen<string>("menu", (event) => handler(event.payload));
}
